name: "Markdown to DOCX Converter"
description: "Converts a Markdown file to a DOCX Word document using Pandoc."
author: "gccloudone"
inputs:
  markdown_file:
    description: "Path to the Markdown file to be converted"
    required: true
  output_file:
    description: "Path to the output DOCX file"
    required: false
    default: "output/output.docx"
  reference_doc:
    description: "Path to the DOCX reference template"
    required: true
    default: "template/ssc-template-v2.7.dotx"

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        pip3 install python-docx

    - name: Run Markdown to DOCX Conversion
      shell: bash
      run: |
        ./convert-to-word.sh "${{ inputs.markdown_file }}" \
                             "${{ inputs.output_file }}" \
                             "${{ inputs.reference_doc }}"
