name: Markdown to Word Conversion

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  markdown-to-word:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Combine All Markdown Files
        run: |
          cat <<EOF > "$RUNNER_TEMP/combined.md"
          ---
          title: "GCCO"
          subtitle: "Markdown to Word"
          date: "$(date +%Y-%m-%d)"
          version: "v0.0.1"
          ---

          \newpage

          ::: {#toc}
          :::

          \newpage
          EOF
          find docs -name "*.md" -not -name "combined.md" -exec sh -c 'cat "$@"; echo' _ {} + >> "$RUNNER_TEMP/combined.md"
          sed -E -i 's|(\.\./)+attachments|attachments|g' "$RUNNER_TEMP/combined.md"

      - name: Convert Markdown to Word
        uses: gccloudone/markdown-to-word@main
        with:
          default_title: "[Untitled Document]"
          markdown_file: "${{ runner.temp }}/combined.md"
          output_file: "output/markdown-to-word.docx"
          reference_doc: "template/ssc-template-v2.7.dotx"

      - name: Upload Word Document
        uses: actions/upload-artifact@v7
        with:
          name: markdown-to-word
          path: output/markdown-to-word.docx
          archive: false
